### PR TITLE
prepare for integration into FS

### PR DESCRIPTION
**Pull request by yhuang43**
handle ARM64 Mac build

### CODE REVIEW

**Comment by ste93ste** [comment]
The PR is causing the CI to stall for Mac OS. 
Do we need to add additional flags in [https://github.com/freesurfer/samseg/blob/dev/.github/workflows/macos_build.sh](url)?

**Comment by yhuang43** [comment]
I added this section to CMakeLists.txt. But if CMAKE_C_COMPILER and CMAKE_CXX_COMPILER are not passed, it goes into infinite configuration loop. Any suggestions? Maybe change setup.py to detect the platform, and hard-coded there?

if(APPLE)
   set(CMAKE_C_COMPILER "/usr/bin/clang")
   set(CMAKE_CXX_COMPILER "/usr/bin/clang++")
   # set -DAPPLE_ARM64=ON on cmake command line for arm64 build
   if(APPLE_ARM64)
      set(CMAKE_OSX_ARCHITECTURES "arm64")
       add_definitions(-DARM64 -DDarwin -DPNG_ARM_NEON_OPT=0)
   endif()
endif()

**Comment by yhuang43** [comment]
darwin_x86_64 works fine w/o the addition. I think I will just change the condition to the top condition to 'if(APPLE_ARM64)' instead of 'if(APPLE)'. But it will be using a different compiler than Freesurfer to compile the bindings.

**Comment by ste93ste** [comment]
Thanks for fixing it!

**Pull request merged**
